{"name": "test_assert_true", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 == 2) == True", "trace": "self = <src.a_pytest.d_assert.test_assert.TestClass object at 0x0000029E1E93B040>\n\n    def test_assert_true(self):\n>       assert (1 == 2) == True\nE       assert (1 == 2) == True\n\nsrc\\a_pytest\\d_assert\\test_assert.py:32: AssertionError"}, "start": 1578630425969, "stop": 1578630425969, "uuid": "2b39b1f0-66fc-4456-9bb9-81e23e678e83", "historyId": "200250795244e6271009351d897d84c0", "testCaseId": "1141cbcd99acc4146b7bb39e523cfe30", "fullName": "src.a_pytest.d_assert.test_assert.TestClass#test_assert_true", "labels": [{"name": "parentSuite", "value": "src.a_pytest.d_assert"}, {"name": "suite", "value": "test_assert"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "GELOMEN-PC"}, {"name": "thread", "value": "9476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.a_pytest.d_assert.test_assert"}]}